//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 军升级表.xlsm SHEET: Sheet1 KEY: level

#pragma once
#pragma pack(1)
struct ArmyLevelBase
{
	DWORD getUniqueID() const { return usage_id_hash(level); }

	DWORD level; // 等级
	DWORD dwMoney; // 升级资金
	DWORD dwGrade; // 升级积分
	DWORD dwMaxCorps; // 团数量
};
#pragma pack()

#if false
namespace table
{
	// 军升级表
	struct zArmyLevelBaseEntry : public zEntry
	{
		DWORD level; // 等级
		DWORD dwMoney; // 升级资金
		DWORD dwGrade; // 升级积分
		DWORD dwMaxCorps; // 团数量

		virtual const char* getClassName() const { return "军升级表"; }
		static const char* getFileName() { return "ArmyLevelBase.tbl"; }
		void fill(const ArmyLevelBase& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			this->dwMoney = base.dwMoney;
			this->dwGrade = base.dwGrade;
			this->dwMaxCorps = base.dwMaxCorps;
		}
		void reset()
		{
			this->level = 0;
			this->dwMoney = 0;
			this->dwGrade = 0;
			this->dwMaxCorps = 0;
		}
	};
	typedef zDataBM<zArmyLevelBaseEntry, ArmyLevelBase> ArmyLevelBaseManager;
}
#endif

