//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 军团装备打造表.xlsm SHEET: Sheet1 KEY: baseid + quality

#pragma once
#pragma pack(1)
struct ArmyEquipMakeDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(baseid, quality); }

	DWORD quality; // 品质
	DWORD baseid; // 编号
	DWORD material; // 魔甲材料
	DWORD price; // 团资金
};
#pragma pack()

#if false
namespace table
{
	// 军团装备打造表
	struct zArmyEquipMakeDataBaseEntry : public zEntry
	{
		DWORD quality; // 品质
		DWORD baseid; // 编号
		DWORD material; // 魔甲材料
		DWORD price; // 团资金

		virtual const char* getClassName() const { return "军团装备打造表"; }
		static const char* getFileName() { return "ArmyEquipMakeDataBase.tbl"; }
		void fill(const ArmyEquipMakeDataBase& base)
		{
			this->id = base.getUniqueID();

			this->quality = base.quality;
			this->baseid = base.baseid;
			this->material = base.material;
			this->price = base.price;
		}
		void reset()
		{
			this->quality = 0;
			this->baseid = 0;
			this->material = 0;
			this->price = 0;
		}
	};
	typedef zDataBM<zArmyEquipMakeDataBaseEntry, ArmyEquipMakeDataBase> ArmyEquipMakeDataBaseManager;
}
#endif

