//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 军团装备基本表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct ArmyEquipDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 编号
	char name[32]; // 名称
	DWORD type; // 分类
	DWORD category; // 类型
	DWORD maxmember; // 承载人数
	DWORD cnumber; // 打造材料
	DWORD dnumber; // 销毁返还材料
	DWORD inumber; // 修理材料
	DWORD imoney; // 修理费用
	DWORD cmoney; // 打造费用
	DWORD clevel; // 打造等级
	DWORD extmember; // 额外承载
	DWORD chart; // 图纸
	DWORD maxhp; // 血量
};
#pragma pack()

#if false
namespace table
{
	// 军团装备基本表
	struct zArmyEquipDataBaseEntry : public zEntry
	{
		DWORD id; // 编号
		char name[32]; // 名称
		DWORD type; // 分类
		DWORD category; // 类型
		DWORD maxmember; // 承载人数
		DWORD cnumber; // 打造材料
		DWORD dnumber; // 销毁返还材料
		DWORD inumber; // 修理材料
		DWORD imoney; // 修理费用
		DWORD cmoney; // 打造费用
		DWORD clevel; // 打造等级
		DWORD extmember; // 额外承载
		DWORD chart; // 图纸
		DWORD maxhp; // 血量

		virtual const char* getClassName() const { return "军团装备基本表"; }
		static const char* getFileName() { return "ArmyEquipDataBase.tbl"; }
		void fill(const ArmyEquipDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			strncpy(this->name, base.name, 32);
			this->type = base.type;
			this->category = base.category;
			this->maxmember = base.maxmember;
			this->cnumber = base.cnumber;
			this->dnumber = base.dnumber;
			this->inumber = base.inumber;
			this->imoney = base.imoney;
			this->cmoney = base.cmoney;
			this->clevel = base.clevel;
			this->extmember = base.extmember;
			this->chart = base.chart;
			this->maxhp = base.maxhp;
		}
		void reset()
		{
			this->id = 0;
			this->name[0] = '\0';
			this->type = 0;
			this->category = 0;
			this->maxmember = 0;
			this->cnumber = 0;
			this->dnumber = 0;
			this->inumber = 0;
			this->imoney = 0;
			this->cmoney = 0;
			this->clevel = 0;
			this->extmember = 0;
			this->chart = 0;
			this->maxhp = 0;
		}
	};
	typedef zDataBM<zArmyEquipDataBaseEntry, ArmyEquipDataBase> ArmyEquipDataBaseManager;
}
#endif

