//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: BOSS刷新信息表.xlsm SHEET: Sheet1 KEY: bosstype + bossid

#pragma once
#pragma pack(1)
struct BossRefreshInfoBase
{
	DWORD getUniqueID() const { return usage_id_hash(bosstype, bossid); }

	DWORD bossid; // BOSS编号
	DWORD bosstype; // 类型
	char name[256]; // 备注
	DWORD mapid; // 地图ID
};
#pragma pack()

#if false
namespace table
{
	// BOSS刷新信息表
	struct zBossRefreshInfoBaseEntry : public zEntry
	{
		DWORD bossid; // BOSS编号
		DWORD bosstype; // 类型
		char name[256]; // 备注
		DWORD mapid; // 地图ID

		virtual const char* getClassName() const { return "BOSS刷新信息表"; }
		static const char* getFileName() { return "BossRefreshInfoBase.tbl"; }
		void fill(const BossRefreshInfoBase& base)
		{
			this->id = base.getUniqueID();

			this->bossid = base.bossid;
			this->bosstype = base.bosstype;
			strncpy(this->name, base.name, 256);
			this->mapid = base.mapid;
		}
		void reset()
		{
			this->bossid = 0;
			this->bosstype = 0;
			this->name[0] = '\0';
			this->mapid = 0;
		}
	};
	typedef zDataBM<zBossRefreshInfoBaseEntry, BossRefreshInfoBase> BossRefreshInfoBaseManager;
}
#endif

