//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: Boss卡片表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct BossCardDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 卡片编号
	DWORD prefix; // 前缀
	char attribute[32]; // 属性生成
};
#pragma pack()

#if false
namespace table
{
	// Boss卡片表
	struct zBossCardDataBaseEntry : public zEntry
	{
		DWORD id; // 卡片编号
		DWORD prefix; // 前缀
		char attribute[32]; // 属性生成

		virtual const char* getClassName() const { return "Boss卡片表"; }
		static const char* getFileName() { return "BossCardDataBase.tbl"; }
		void fill(const BossCardDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			this->prefix = base.prefix;
			strncpy(this->attribute, base.attribute, 32);
		}
		void reset()
		{
			this->id = 0;
			this->prefix = 0;
			this->attribute[0] = '\0';
		}
	};
	typedef zDataBM<zBossCardDataBaseEntry, BossCardDataBase> BossCardDataBaseManager;
}
#endif

