//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 团建筑升级表.xlsm SHEET: Sheet1 KEY: byType + byLevel

#pragma once
#pragma pack(1)
struct BuildingLevelBase
{
	DWORD getUniqueID() const { return usage_id_hash(byType, byLevel); }

	DWORD byLevel; // 等级
	DWORD byType; // 类型
	DWORD dwGlory; // 升级繁荣度
	DWORD dwMoney; // 升级团资金
	DWORD dwRunGlory; // 维护繁荣度
	DWORD dwRunMoney; // 维护团资金
	DWORD dwNpcid; // 建筑NPC
	DWORD dwPosx; // 位置X
	DWORD dwPosy; // 位置Y
	DWORD dwCorpsPack; // 团包裹格子
	DWORD dwCorpsMoney; // 团维护资金
	DWORD dwMaxMember; // 人数上限
	DWORD dwMaxPack; // 奖箱格子
	DWORD dwMaxHealth; // 营养指数上限
	DWORD dwMaxGlory; // 繁荣度上限
	DWORD dwMaxMoney; // 资金上限
	char name[32]; // 名称
};
#pragma pack()

#if false
namespace table
{
	// 团建筑升级表
	struct zBuildingLevelBaseEntry : public zEntry
	{
		DWORD byLevel; // 等级
		DWORD byType; // 类型
		DWORD dwGlory; // 升级繁荣度
		DWORD dwMoney; // 升级团资金
		DWORD dwRunGlory; // 维护繁荣度
		DWORD dwRunMoney; // 维护团资金
		DWORD dwNpcid; // 建筑NPC
		DWORD dwPosx; // 位置X
		DWORD dwPosy; // 位置Y
		DWORD dwCorpsPack; // 团包裹格子
		DWORD dwCorpsMoney; // 团维护资金
		DWORD dwMaxMember; // 人数上限
		DWORD dwMaxPack; // 奖箱格子
		DWORD dwMaxHealth; // 营养指数上限
		DWORD dwMaxGlory; // 繁荣度上限
		DWORD dwMaxMoney; // 资金上限
		char name[32]; // 名称

		virtual const char* getClassName() const { return "团建筑升级表"; }
		static const char* getFileName() { return "BuildingLevelBase.tbl"; }
		void fill(const BuildingLevelBase& base)
		{
			this->id = base.getUniqueID();

			this->byLevel = base.byLevel;
			this->byType = base.byType;
			this->dwGlory = base.dwGlory;
			this->dwMoney = base.dwMoney;
			this->dwRunGlory = base.dwRunGlory;
			this->dwRunMoney = base.dwRunMoney;
			this->dwNpcid = base.dwNpcid;
			this->dwPosx = base.dwPosx;
			this->dwPosy = base.dwPosy;
			this->dwCorpsPack = base.dwCorpsPack;
			this->dwCorpsMoney = base.dwCorpsMoney;
			this->dwMaxMember = base.dwMaxMember;
			this->dwMaxPack = base.dwMaxPack;
			this->dwMaxHealth = base.dwMaxHealth;
			this->dwMaxGlory = base.dwMaxGlory;
			this->dwMaxMoney = base.dwMaxMoney;
			strncpy(this->name, base.name, 32);
		}
		void reset()
		{
			this->byLevel = 0;
			this->byType = 0;
			this->dwGlory = 0;
			this->dwMoney = 0;
			this->dwRunGlory = 0;
			this->dwRunMoney = 0;
			this->dwNpcid = 0;
			this->dwPosx = 0;
			this->dwPosy = 0;
			this->dwCorpsPack = 0;
			this->dwCorpsMoney = 0;
			this->dwMaxMember = 0;
			this->dwMaxPack = 0;
			this->dwMaxHealth = 0;
			this->dwMaxGlory = 0;
			this->dwMaxMoney = 0;
			this->name[0] = '\0';
		}
	};
	typedef zDataBM<zBuildingLevelBaseEntry, BuildingLevelBase> BuildingLevelBaseManager;
}
#endif

