//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 冷却.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct ColdDownDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 编号
	char name[32]; // 名称
	DWORD coldtype; // 间隔类型
	DWORD maxtimes; // 使用次数
};
#pragma pack()

#if false
namespace table
{
	// 冷却
	struct zColdDownDataBaseEntry : public zEntry
	{
		DWORD id; // 编号
		char name[32]; // 名称
		DWORD coldtype; // 间隔类型
		DWORD maxtimes; // 使用次数

		virtual const char* getClassName() const { return "冷却"; }
		static const char* getFileName() { return "ColdDownDataBase.tbl"; }
		void fill(const ColdDownDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			strncpy(this->name, base.name, 32);
			this->coldtype = base.coldtype;
			this->maxtimes = base.maxtimes;
		}
		void reset()
		{
			this->id = 0;
			this->name[0] = '\0';
			this->coldtype = 0;
			this->maxtimes = 0;
		}
	};
	typedef zDataBM<zColdDownDataBaseEntry, ColdDownDataBase> ColdDownDataBaseManager;
}
#endif

