//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 奇异兽职业技能领悟表.xlsm SHEET: Sheet1 KEY: level

#pragma once
#pragma pack(1)
struct DemonSkillDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(level); }

	DWORD level; // 领悟等级
	char demonskill1[2048]; // 战宠领悟技能几率
	char demonskill2[2048]; // 侍宠领悟技能几率
	char demonskill3[2048]; // 蓝色品质
	char demonskill4[2048]; // 黄色品质
	char demonskill5[2048]; // 绿色品质
	char demonskill6[2048]; // 紫色品质
};
#pragma pack()

#if false
namespace table
{
	// 奇异兽职业技能领悟表
	struct zDemonSkillDataBaseEntry : public zEntry
	{
		DWORD level; // 领悟等级
		char demonskill1[2048]; // 战宠领悟技能几率
		char demonskill2[2048]; // 侍宠领悟技能几率
		char demonskill3[2048]; // 蓝色品质
		char demonskill4[2048]; // 黄色品质
		char demonskill5[2048]; // 绿色品质
		char demonskill6[2048]; // 紫色品质

		virtual const char* getClassName() const { return "奇异兽职业技能领悟表"; }
		static const char* getFileName() { return "DemonSkillDataBase.tbl"; }
		void fill(const DemonSkillDataBase& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			strncpy(this->demonskill1, base.demonskill1, 2048);
			strncpy(this->demonskill2, base.demonskill2, 2048);
			strncpy(this->demonskill3, base.demonskill3, 2048);
			strncpy(this->demonskill4, base.demonskill4, 2048);
			strncpy(this->demonskill5, base.demonskill5, 2048);
			strncpy(this->demonskill6, base.demonskill6, 2048);
		}
		void reset()
		{
			this->level = 0;
			this->demonskill1[0] = '\0';
			this->demonskill2[0] = '\0';
			this->demonskill3[0] = '\0';
			this->demonskill4[0] = '\0';
			this->demonskill5[0] = '\0';
			this->demonskill6[0] = '\0';
		}
	};
	typedef zDataBM<zDemonSkillDataBaseEntry, DemonSkillDataBase> DemonSkillDataBaseManager;
}
#endif

