//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 奇异兽升级表.xlsm SHEET: Sheet1 KEY: level

#pragma once
#pragma pack(1)
struct DemonLevelUpData
{
	DWORD getUniqueID() const { return usage_id_hash(level); }

	DWORD level; // 等级
	DWORD exp_white; // 白色经验
	DWORD exp_blue; // 蓝色经验
	DWORD exp_yellow; // 黄色经验
	DWORD exp_green; // 绿色经验
	DWORD exp_purple; // 紫色经验
	DWORD exp_orange; // 橙色经验
	DWORD damge_white; // 白色伤害
	DWORD damge_blue; // 蓝色伤害
	DWORD damge_yellow; // 黄色伤害
	DWORD damge_green; // 绿色伤害
	DWORD damge_purple; // 紫色伤害
	DWORD damge_orange; // 橙色伤害
};
#pragma pack()

#if false
namespace table
{
	// 奇异兽升级表
	struct zDemonLevelUpDataEntry : public zEntry
	{
		DWORD level; // 等级
		DWORD exp_white; // 白色经验
		DWORD exp_blue; // 蓝色经验
		DWORD exp_yellow; // 黄色经验
		DWORD exp_green; // 绿色经验
		DWORD exp_purple; // 紫色经验
		DWORD exp_orange; // 橙色经验
		DWORD damge_white; // 白色伤害
		DWORD damge_blue; // 蓝色伤害
		DWORD damge_yellow; // 黄色伤害
		DWORD damge_green; // 绿色伤害
		DWORD damge_purple; // 紫色伤害
		DWORD damge_orange; // 橙色伤害

		virtual const char* getClassName() const { return "奇异兽升级表"; }
		static const char* getFileName() { return "DemonLevelUpData.tbl"; }
		void fill(const DemonLevelUpData& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			this->exp_white = base.exp_white;
			this->exp_blue = base.exp_blue;
			this->exp_yellow = base.exp_yellow;
			this->exp_green = base.exp_green;
			this->exp_purple = base.exp_purple;
			this->exp_orange = base.exp_orange;
			this->damge_white = base.damge_white;
			this->damge_blue = base.damge_blue;
			this->damge_yellow = base.damge_yellow;
			this->damge_green = base.damge_green;
			this->damge_purple = base.damge_purple;
			this->damge_orange = base.damge_orange;
		}
		void reset()
		{
			this->level = 0;
			this->exp_white = 0;
			this->exp_blue = 0;
			this->exp_yellow = 0;
			this->exp_green = 0;
			this->exp_purple = 0;
			this->exp_orange = 0;
			this->damge_white = 0;
			this->damge_blue = 0;
			this->damge_yellow = 0;
			this->damge_green = 0;
			this->damge_purple = 0;
			this->damge_orange = 0;
		}
	};
	typedef zDataBM<zDemonLevelUpDataEntry, DemonLevelUpData> DemonLevelUpDataManager;
}
#endif

