//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 奇异兽扭蛋表.xlsm SHEET: Sheet1 KEY: gettype + quality

#pragma once
#pragma pack(1)
struct DemonGetDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(gettype, quality); }

	DWORD quality; // 品质
	DWORD gettype; // 获取类型
	char demonlibrary[256]; // 宠物库
	DWORD ratio; // 概率
	DWORD price; // 费用
	DWORD pricetype; // 费用类型
	DWORD discount; // 连抽折扣
	DWORD freecount; // 免费次数
	char freetimes[256]; // 免费时间间隔
	DWORD freecountresettype; // 免费次数重置周期
	DWORD freetimetype; // 免费时间间隔单位
};
#pragma pack()

#if false
namespace table
{
	// 奇异兽扭蛋表
	struct zDemonGetDataBaseEntry : public zEntry
	{
		DWORD quality; // 品质
		DWORD gettype; // 获取类型
		char demonlibrary[256]; // 宠物库
		DWORD ratio; // 概率
		DWORD price; // 费用
		DWORD pricetype; // 费用类型
		DWORD discount; // 连抽折扣
		DWORD freecount; // 免费次数
		char freetimes[256]; // 免费时间间隔
		DWORD freecountresettype; // 免费次数重置周期
		DWORD freetimetype; // 免费时间间隔单位

		virtual const char* getClassName() const { return "奇异兽扭蛋表"; }
		static const char* getFileName() { return "DemonGetDataBase.tbl"; }
		void fill(const DemonGetDataBase& base)
		{
			this->id = base.getUniqueID();

			this->quality = base.quality;
			this->gettype = base.gettype;
			strncpy(this->demonlibrary, base.demonlibrary, 256);
			this->ratio = base.ratio;
			this->price = base.price;
			this->pricetype = base.pricetype;
			this->discount = base.discount;
			this->freecount = base.freecount;
			strncpy(this->freetimes, base.freetimes, 256);
			this->freecountresettype = base.freecountresettype;
			this->freetimetype = base.freetimetype;
		}
		void reset()
		{
			this->quality = 0;
			this->gettype = 0;
			this->demonlibrary[0] = '\0';
			this->ratio = 0;
			this->price = 0;
			this->pricetype = 0;
			this->discount = 0;
			this->freecount = 0;
			this->freetimes[0] = '\0';
			this->freecountresettype = 0;
			this->freetimetype = 0;
		}
	};
	typedef zDataBM<zDemonGetDataBaseEntry, DemonGetDataBase> DemonGetDataBaseManager;
}
#endif

