//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 装备升星表.xlsm SHEET: Sheet1 KEY: equipid + level

#pragma once
#pragma pack(1)
struct EquipLevelDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(equipid, level); }

	DWORD level; // 强化等级
	DWORD equipid; // 强化ID
	DWORD success; // 服务器成功率
	DWORD pdam; // 物攻
	DWORD mdam; // 化攻
	DWORD pdef; // 物防
	DWORD mdef; // 化防
	DWORD maxhp; // 生命值
	DWORD needmoney; // 需要金钱
	DWORD punishlevel; // 惩罚等级
	DWORD addneedlevel; // 需求等级增加
	DWORD addrate; // 服务器完美增加
	DWORD remove; // 是否会爆
	DWORD material; // 消耗材料
	DWORD materialnum; // 材料个数
	DWORD ratedown; // 失败增加几率
	DWORD ratedowntime; // 失败增加几率时间
};
#pragma pack()

#if false
namespace table
{
	// 装备升星表
	struct zEquipLevelDataBaseEntry : public zEntry
	{
		DWORD level; // 强化等级
		DWORD equipid; // 强化ID
		DWORD success; // 服务器成功率
		DWORD pdam; // 物攻
		DWORD mdam; // 化攻
		DWORD pdef; // 物防
		DWORD mdef; // 化防
		DWORD maxhp; // 生命值
		DWORD needmoney; // 需要金钱
		DWORD punishlevel; // 惩罚等级
		DWORD addneedlevel; // 需求等级增加
		DWORD addrate; // 服务器完美增加
		DWORD remove; // 是否会爆
		DWORD material; // 消耗材料
		DWORD materialnum; // 材料个数
		DWORD ratedown; // 失败增加几率
		DWORD ratedowntime; // 失败增加几率时间

		virtual const char* getClassName() const { return "装备升星表"; }
		static const char* getFileName() { return "EquipLevelDataBase.tbl"; }
		void fill(const EquipLevelDataBase& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			this->equipid = base.equipid;
			this->success = base.success;
			this->pdam = base.pdam;
			this->mdam = base.mdam;
			this->pdef = base.pdef;
			this->mdef = base.mdef;
			this->maxhp = base.maxhp;
			this->needmoney = base.needmoney;
			this->punishlevel = base.punishlevel;
			this->addneedlevel = base.addneedlevel;
			this->addrate = base.addrate;
			this->remove = base.remove;
			this->material = base.material;
			this->materialnum = base.materialnum;
			this->ratedown = base.ratedown;
			this->ratedowntime = base.ratedowntime;
		}
		void reset()
		{
			this->level = 0;
			this->equipid = 0;
			this->success = 0;
			this->pdam = 0;
			this->mdam = 0;
			this->pdef = 0;
			this->mdef = 0;
			this->maxhp = 0;
			this->needmoney = 0;
			this->punishlevel = 0;
			this->addneedlevel = 0;
			this->addrate = 0;
			this->remove = 0;
			this->material = 0;
			this->materialnum = 0;
			this->ratedown = 0;
			this->ratedowntime = 0;
		}
	};
	typedef zDataBM<zEquipLevelDataBaseEntry, EquipLevelDataBase> EquipLevelDataBaseManager;
}
#endif

