//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 装备神魂表.xlsm SHEET: Sheet1 KEY: equipid + soulgrade + soullevel

#pragma once
#pragma pack(1)
struct EquipGodSoulBase
{
	DWORD getUniqueID() const { return usage_id_hash(equipid, soulgrade, soullevel); }

	WORD soullevel; // 神魂段数
	WORD soulgrade; // 神魂阶数
	DWORD equipid; // 装备ID
	DWORD rate; // 对应成功率
	DWORD addrate; // 完美增加几率
	DWORD pdam; // 物攻
	DWORD mdam; // 化攻
	DWORD pdef; // 物防
	DWORD mdef; // 化防
	DWORD hp; // 生命值
	DWORD needmoney; // 需要金钱
	DWORD neednum; // 消耗材料
};
#pragma pack()

#if false
namespace table
{
	// 装备神魂表
	struct zEquipGodSoulBaseEntry : public zEntry
	{
		WORD soullevel; // 神魂段数
		WORD soulgrade; // 神魂阶数
		DWORD equipid; // 装备ID
		DWORD rate; // 对应成功率
		DWORD addrate; // 完美增加几率
		DWORD pdam; // 物攻
		DWORD mdam; // 化攻
		DWORD pdef; // 物防
		DWORD mdef; // 化防
		DWORD hp; // 生命值
		DWORD needmoney; // 需要金钱
		DWORD neednum; // 消耗材料

		virtual const char* getClassName() const { return "装备神魂表"; }
		static const char* getFileName() { return "EquipGodSoulBase.tbl"; }
		void fill(const EquipGodSoulBase& base)
		{
			this->id = base.getUniqueID();

			this->soullevel = base.soullevel;
			this->soulgrade = base.soulgrade;
			this->equipid = base.equipid;
			this->rate = base.rate;
			this->addrate = base.addrate;
			this->pdam = base.pdam;
			this->mdam = base.mdam;
			this->pdef = base.pdef;
			this->mdef = base.mdef;
			this->hp = base.hp;
			this->needmoney = base.needmoney;
			this->neednum = base.neednum;
		}
		void reset()
		{
			this->soullevel = 0;
			this->soulgrade = 0;
			this->equipid = 0;
			this->rate = 0;
			this->addrate = 0;
			this->pdam = 0;
			this->mdam = 0;
			this->pdef = 0;
			this->mdef = 0;
			this->hp = 0;
			this->needmoney = 0;
			this->neednum = 0;
		}
	};
	typedef zDataBM<zEquipGodSoulBaseEntry, EquipGodSoulBase> EquipGodSoulBaseManager;
}
#endif

