//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: Item表格.xlsm SHEET: 装备类 KEY: equip_id

#pragma once
#pragma pack(1)
struct EquipDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(equip_id); }

	DWORD equip_id; // 装备ID
	BYTE equip_pos; // 装备部位
	DWORD pdam_min; // 物理攻击下限
	DWORD pdam_max; // 物理攻击上限
	DWORD mdam_min; // 法术攻击下限
	DWORD mdam_max; // 法术攻击上限
	DWORD pdef_min; // 物理防御上限
	DWORD pdef_max; // 物理防御下限
	DWORD mdef_min; // 法术防御下限
	DWORD mdef_max; // 法术防御上限
	DWORD max_durable; // 最大耐久度
	DWORD prop_id; // 随机属性
};
#pragma pack()

#if false
namespace table
{
	// Item表格
	struct zEquipDataBaseEntry : public zEntry
	{
		DWORD equip_id; // 装备ID
		BYTE equip_pos; // 装备部位
		DWORD pdam_min; // 物理攻击下限
		DWORD pdam_max; // 物理攻击上限
		DWORD mdam_min; // 法术攻击下限
		DWORD mdam_max; // 法术攻击上限
		DWORD pdef_min; // 物理防御上限
		DWORD pdef_max; // 物理防御下限
		DWORD mdef_min; // 法术防御下限
		DWORD mdef_max; // 法术防御上限
		DWORD max_durable; // 最大耐久度
		DWORD prop_id; // 随机属性

		virtual const char* getClassName() const { return "Item表格"; }
		static const char* getFileName() { return "EquipDataBase.tbl"; }
		void fill(const EquipDataBase& base)
		{
			this->id = base.getUniqueID();

			this->equip_id = base.equip_id;
			this->equip_pos = base.equip_pos;
			this->pdam_min = base.pdam_min;
			this->pdam_max = base.pdam_max;
			this->mdam_min = base.mdam_min;
			this->mdam_max = base.mdam_max;
			this->pdef_min = base.pdef_min;
			this->pdef_max = base.pdef_max;
			this->mdef_min = base.mdef_min;
			this->mdef_max = base.mdef_max;
			this->max_durable = base.max_durable;
			this->prop_id = base.prop_id;
		}
		void reset()
		{
			this->equip_id = 0;
			this->equip_pos = 0;
			this->pdam_min = 0;
			this->pdam_max = 0;
			this->mdam_min = 0;
			this->mdam_max = 0;
			this->pdef_min = 0;
			this->pdef_max = 0;
			this->mdef_min = 0;
			this->mdef_max = 0;
			this->max_durable = 0;
			this->prop_id = 0;
		}
	};
	typedef zDataBM<zEquipDataBaseEntry, EquipDataBase> EquipDataBaseManager;
}
#endif

