//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 灵魂属性表.xlsm SHEET: Sheet1 KEY: type + quality

#pragma once
#pragma pack(1)
struct EquipSoulDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(type, quality); }

	DWORD quality; // 材料品质
	DWORD type; // 装备类别
	char soulhit[64]; // 致命一击
	char soulignoredef[64]; // 忽视防御
	char soulbang[64]; // 重击
	char soulhurtecho[64]; // 伤害反射
	char soulphurtsub[64]; // 物伤减少
	char soulmhurtsub[64]; // 化伤减少
	char soulmaxhpadd[64]; // 生命值增加
};
#pragma pack()

#if false
namespace table
{
	// 灵魂属性表
	struct zEquipSoulDataBaseEntry : public zEntry
	{
		DWORD quality; // 材料品质
		DWORD type; // 装备类别
		char soulhit[64]; // 致命一击
		char soulignoredef[64]; // 忽视防御
		char soulbang[64]; // 重击
		char soulhurtecho[64]; // 伤害反射
		char soulphurtsub[64]; // 物伤减少
		char soulmhurtsub[64]; // 化伤减少
		char soulmaxhpadd[64]; // 生命值增加

		virtual const char* getClassName() const { return "灵魂属性表"; }
		static const char* getFileName() { return "EquipSoulDataBase.tbl"; }
		void fill(const EquipSoulDataBase& base)
		{
			this->id = base.getUniqueID();

			this->quality = base.quality;
			this->type = base.type;
			strncpy(this->soulhit, base.soulhit, 64);
			strncpy(this->soulignoredef, base.soulignoredef, 64);
			strncpy(this->soulbang, base.soulbang, 64);
			strncpy(this->soulhurtecho, base.soulhurtecho, 64);
			strncpy(this->soulphurtsub, base.soulphurtsub, 64);
			strncpy(this->soulmhurtsub, base.soulmhurtsub, 64);
			strncpy(this->soulmaxhpadd, base.soulmaxhpadd, 64);
		}
		void reset()
		{
			this->quality = 0;
			this->type = 0;
			this->soulhit[0] = '\0';
			this->soulignoredef[0] = '\0';
			this->soulbang[0] = '\0';
			this->soulhurtecho[0] = '\0';
			this->soulphurtsub[0] = '\0';
			this->soulmhurtsub[0] = '\0';
			this->soulmaxhpadd[0] = '\0';
		}
	};
	typedef zDataBM<zEquipSoulDataBaseEntry, EquipSoulDataBase> EquipSoulDataBaseManager;
}
#endif

