//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 职务权限表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct FunctionRightBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 编号
	char name[32]; // 名称
	char funset[32]; // 权利职务
};
#pragma pack()

#if false
namespace table
{
	// 职务权限表
	struct zFunctionRightBaseEntry : public zEntry
	{
		DWORD id; // 编号
		char name[32]; // 名称
		char funset[32]; // 权利职务

		virtual const char* getClassName() const { return "职务权限表"; }
		static const char* getFileName() { return "FunctionRightBase.tbl"; }
		void fill(const FunctionRightBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			strncpy(this->name, base.name, 32);
			strncpy(this->funset, base.funset, 32);
		}
		void reset()
		{
			this->id = 0;
			this->name[0] = '\0';
			this->funset[0] = '\0';
		}
	};
	typedef zDataBM<zFunctionRightBaseEntry, FunctionRightBase> FunctionRightBaseManager;
}
#endif

