//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 团购表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct GrouponDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 礼包ID
	char name[32]; // 礼包名称
	DWORD buytimes; // 限购次数
	DWORD moneytype; // 货币类型
	DWORD currentprice; // 现价
	char item_1[128]; // 道具1
	char item_2[128]; // 道具2
	char item_3[128]; // 道具3
	char item_4[128]; // 道具4
	char item_5[128]; // 道具5
	char item_6[128]; // 道具6
};
#pragma pack()

#if false
namespace table
{
	// 团购表
	struct zGrouponDataBaseEntry : public zEntry
	{
		DWORD id; // 礼包ID
		char name[32]; // 礼包名称
		DWORD buytimes; // 限购次数
		DWORD moneytype; // 货币类型
		DWORD currentprice; // 现价
		char item_1[128]; // 道具1
		char item_2[128]; // 道具2
		char item_3[128]; // 道具3
		char item_4[128]; // 道具4
		char item_5[128]; // 道具5
		char item_6[128]; // 道具6

		virtual const char* getClassName() const { return "团购表"; }
		static const char* getFileName() { return "GrouponDataBase.tbl"; }
		void fill(const GrouponDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			strncpy(this->name, base.name, 32);
			this->buytimes = base.buytimes;
			this->moneytype = base.moneytype;
			this->currentprice = base.currentprice;
			strncpy(this->item_1, base.item_1, 128);
			strncpy(this->item_2, base.item_2, 128);
			strncpy(this->item_3, base.item_3, 128);
			strncpy(this->item_4, base.item_4, 128);
			strncpy(this->item_5, base.item_5, 128);
			strncpy(this->item_6, base.item_6, 128);
		}
		void reset()
		{
			this->id = 0;
			this->name[0] = '\0';
			this->buytimes = 0;
			this->moneytype = 0;
			this->currentprice = 0;
			this->item_1[0] = '\0';
			this->item_2[0] = '\0';
			this->item_3[0] = '\0';
			this->item_4[0] = '\0';
			this->item_5[0] = '\0';
			this->item_6[0] = '\0';
		}
	};
	typedef zDataBM<zGrouponDataBaseEntry, GrouponDataBase> GrouponDataBaseManager;
}
#endif

