//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 坐骑纹章炼化表.xlsm SHEET: Sheet1 KEY: equipid + level

#pragma once
#pragma pack(1)
struct HorseEquipRefinementBase
{
	DWORD getUniqueID() const { return usage_id_hash(equipid, level); }

	WORD level; // 炼化等级
	WORD equipid; // 纹章ID
	DWORD successrate; // 成功几率
	DWORD falselevel; // 失败后等级
	DWORD pdam; // 物攻提升
	DWORD mdam; // 化攻提升
	DWORD pdef; // 物防提升
	DWORD mdef; // 化防提升
	DWORD maxhp; // 生命值提升
	DWORD needmoney; // 需要金钱
	DWORD dwField10; // 需要炼化强度
};
#pragma pack()

#if false
namespace table
{
	// 坐骑纹章炼化表
	struct zHorseEquipRefinementBaseEntry : public zEntry
	{
		WORD level; // 炼化等级
		WORD equipid; // 纹章ID
		DWORD successrate; // 成功几率
		DWORD falselevel; // 失败后等级
		DWORD pdam; // 物攻提升
		DWORD mdam; // 化攻提升
		DWORD pdef; // 物防提升
		DWORD mdef; // 化防提升
		DWORD maxhp; // 生命值提升
		DWORD needmoney; // 需要金钱
		DWORD dwField10; // 需要炼化强度

		virtual const char* getClassName() const { return "坐骑纹章炼化表"; }
		static const char* getFileName() { return "HorseEquipRefinementBase.tbl"; }
		void fill(const HorseEquipRefinementBase& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			this->equipid = base.equipid;
			this->successrate = base.successrate;
			this->falselevel = base.falselevel;
			this->pdam = base.pdam;
			this->mdam = base.mdam;
			this->pdef = base.pdef;
			this->mdef = base.mdef;
			this->maxhp = base.maxhp;
			this->needmoney = base.needmoney;
			this->dwField10 = base.dwField10;
		}
		void reset()
		{
			this->level = 0;
			this->equipid = 0;
			this->successrate = 0;
			this->falselevel = 0;
			this->pdam = 0;
			this->mdam = 0;
			this->pdef = 0;
			this->mdef = 0;
			this->maxhp = 0;
			this->needmoney = 0;
			this->dwField10 = 0;
		}
	};
	typedef zDataBM<zHorseEquipRefinementBaseEntry, HorseEquipRefinementBase> HorseEquipRefinementBaseManager;
}
#endif

