//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 坐骑培育表.xlsm SHEET: Sheet1 KEY: horseid

#pragma once
#pragma pack(1)
struct HorseBreedBase
{
	DWORD getUniqueID() const { return usage_id_hash(horseid); }

	DWORD horseid; // 坐骑ID
	DWORD level; // 等阶
	DWORD nextlevelid; // 进阶ID
	DWORD zvaluescore; // 坐骑资质分
	DWORD itemid; // 进阶道具ID
	DWORD speed; // 坐骑速度
	DWORD addrateoffhorse; // 下马属性
	DWORD needmoney; // 喂养花费
	DWORD maxsingle; // 单项资质上限
	DWORD activeitemid; // 激活道具ID
	DWORD activeitemnum; // 激活道具数量
	DWORD inheritDressedID; // 外观继承消耗材料ID
	DWORD inheritDressedNum; // 外观继承消耗材料数量
};
#pragma pack()

#if false
namespace table
{
	// 坐骑培育表
	struct zHorseBreedBaseEntry : public zEntry
	{
		DWORD horseid; // 坐骑ID
		DWORD level; // 等阶
		DWORD nextlevelid; // 进阶ID
		DWORD zvaluescore; // 坐骑资质分
		DWORD itemid; // 进阶道具ID
		DWORD speed; // 坐骑速度
		DWORD addrateoffhorse; // 下马属性
		DWORD needmoney; // 喂养花费
		DWORD maxsingle; // 单项资质上限
		DWORD activeitemid; // 激活道具ID
		DWORD activeitemnum; // 激活道具数量
		DWORD inheritDressedID; // 外观继承消耗材料ID
		DWORD inheritDressedNum; // 外观继承消耗材料数量

		virtual const char* getClassName() const { return "坐骑培育表"; }
		static const char* getFileName() { return "HorseBreedBase.tbl"; }
		void fill(const HorseBreedBase& base)
		{
			this->id = base.getUniqueID();

			this->horseid = base.horseid;
			this->level = base.level;
			this->nextlevelid = base.nextlevelid;
			this->zvaluescore = base.zvaluescore;
			this->itemid = base.itemid;
			this->speed = base.speed;
			this->addrateoffhorse = base.addrateoffhorse;
			this->needmoney = base.needmoney;
			this->maxsingle = base.maxsingle;
			this->activeitemid = base.activeitemid;
			this->activeitemnum = base.activeitemnum;
			this->inheritDressedID = base.inheritDressedID;
			this->inheritDressedNum = base.inheritDressedNum;
		}
		void reset()
		{
			this->horseid = 0;
			this->level = 0;
			this->nextlevelid = 0;
			this->zvaluescore = 0;
			this->itemid = 0;
			this->speed = 0;
			this->addrateoffhorse = 0;
			this->needmoney = 0;
			this->maxsingle = 0;
			this->activeitemid = 0;
			this->activeitemnum = 0;
			this->inheritDressedID = 0;
			this->inheritDressedNum = 0;
		}
	};
	typedef zDataBM<zHorseBreedBaseEntry, HorseBreedBase> HorseBreedBaseManager;
}
#endif

