//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 邀请合成表.xlsm SHEET: Sheet1 KEY: itemid1

#pragma once
#pragma pack(1)
struct InviteComposeDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(itemid1); }

	DWORD itemid1; // 道具1
	DWORD itemid2; // 道具2
	DWORD targetid; // 目标道具
};
#pragma pack()

#if false
namespace table
{
	// 邀请合成表
	struct zInviteComposeDataBaseEntry : public zEntry
	{
		DWORD itemid1; // 道具1
		DWORD itemid2; // 道具2
		DWORD targetid; // 目标道具

		virtual const char* getClassName() const { return "邀请合成表"; }
		static const char* getFileName() { return "InviteComposeDataBase.tbl"; }
		void fill(const InviteComposeDataBase& base)
		{
			this->id = base.getUniqueID();

			this->itemid1 = base.itemid1;
			this->itemid2 = base.itemid2;
			this->targetid = base.targetid;
		}
		void reset()
		{
			this->itemid1 = 0;
			this->itemid2 = 0;
			this->targetid = 0;
		}
	};
	typedef zDataBM<zInviteComposeDataBaseEntry, InviteComposeDataBase> InviteComposeDataBaseManager;
}
#endif

