//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 人物升级表.xlsm SHEET: Sheet1 KEY: level

#pragma once
#pragma pack(1)
struct LevelDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(level); }

	DWORD level; // 人物等级
	DWORD exp; // 升级经验
	DWORD maxhp; // 最大生命
	DWORD maxsp; // 最大体力
	DWORD maxjl; // 最大精力
	DWORD ppoint; // 属性点数
	DWORD spoint; // 技能点数
	DWORD maxmoney; // 银币上限
	DWORD maxmoneyticket; // 铜币上限
};
#pragma pack()

#if false
namespace table
{
	// 人物升级表
	struct zLevelDataBaseEntry : public zEntry
	{
		DWORD level; // 人物等级
		DWORD exp; // 升级经验
		DWORD maxhp; // 最大生命
		DWORD maxsp; // 最大体力
		DWORD maxjl; // 最大精力
		DWORD ppoint; // 属性点数
		DWORD spoint; // 技能点数
		DWORD maxmoney; // 银币上限
		DWORD maxmoneyticket; // 铜币上限

		virtual const char* getClassName() const { return "人物升级表"; }
		static const char* getFileName() { return "LevelDataBase.tbl"; }
		void fill(const LevelDataBase& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			this->exp = base.exp;
			this->maxhp = base.maxhp;
			this->maxsp = base.maxsp;
			this->maxjl = base.maxjl;
			this->ppoint = base.ppoint;
			this->spoint = base.spoint;
			this->maxmoney = base.maxmoney;
			this->maxmoneyticket = base.maxmoneyticket;
		}
		void reset()
		{
			this->level = 0;
			this->exp = 0;
			this->maxhp = 0;
			this->maxsp = 0;
			this->maxjl = 0;
			this->ppoint = 0;
			this->spoint = 0;
			this->maxmoney = 0;
			this->maxmoneyticket = 0;
		}
	};
	typedef zDataBM<zLevelDataBaseEntry, LevelDataBase> LevelDataBaseManager;
}
#endif

