//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 生命存储仪升级表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct LifeStoreInstrument
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 存储仪编号
	DWORD needstonenum; // 血精石个数
	DWORD needstonelevel; // 血精石等级
	DWORD successrate; // 成功几率
	DWORD failto; // 失败生命仪
	DWORD fee; // 手续费
	DWORD addlife_white; // 白血量
	DWORD addlife_blue; // 蓝血量
	DWORD addlife_yellow; // 黄血量
	DWORD addlife_green; // 绿血量
	DWORD needrolelevel; // 需求人物等级
	DWORD successto; // 目标生命仪
};
#pragma pack()

#if false
namespace table
{
	// 生命存储仪升级表
	struct zLifeStoreInstrumentEntry : public zEntry
	{
		DWORD id; // 存储仪编号
		DWORD needstonenum; // 血精石个数
		DWORD needstonelevel; // 血精石等级
		DWORD successrate; // 成功几率
		DWORD failto; // 失败生命仪
		DWORD fee; // 手续费
		DWORD addlife_white; // 白血量
		DWORD addlife_blue; // 蓝血量
		DWORD addlife_yellow; // 黄血量
		DWORD addlife_green; // 绿血量
		DWORD needrolelevel; // 需求人物等级
		DWORD successto; // 目标生命仪

		virtual const char* getClassName() const { return "生命存储仪升级表"; }
		static const char* getFileName() { return "LifeStoreInstrument.tbl"; }
		void fill(const LifeStoreInstrument& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			this->needstonenum = base.needstonenum;
			this->needstonelevel = base.needstonelevel;
			this->successrate = base.successrate;
			this->failto = base.failto;
			this->fee = base.fee;
			this->addlife_white = base.addlife_white;
			this->addlife_blue = base.addlife_blue;
			this->addlife_yellow = base.addlife_yellow;
			this->addlife_green = base.addlife_green;
			this->needrolelevel = base.needrolelevel;
			this->successto = base.successto;
		}
		void reset()
		{
			this->id = 0;
			this->needstonenum = 0;
			this->needstonelevel = 0;
			this->successrate = 0;
			this->failto = 0;
			this->fee = 0;
			this->addlife_white = 0;
			this->addlife_blue = 0;
			this->addlife_yellow = 0;
			this->addlife_green = 0;
			this->needrolelevel = 0;
			this->successto = 0;
		}
	};
	typedef zDataBM<zLifeStoreInstrumentEntry, LifeStoreInstrument> LifeStoreInstrumentManager;
}
#endif

