//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 声望军衔表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct MilitaryRankDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 军衔编号
	char name[32]; // 名称
	DWORD needlevel; // 需要等级
	DWORD needprestige; // 需要声望
	DWORD maxcontri; // 功勋上限
	DWORD dayconsume; // 每日消耗
	DWORD maxprestige; // 声望上限
	DWORD paymodulus; // 税收工资
	DWORD damadd; // 增加攻击
	DWORD payticket; // 福利铜币
	DWORD skillpoint; // 技能点数
};
#pragma pack()

#if false
namespace table
{
	// 声望军衔表
	struct zMilitaryRankDataBaseEntry : public zEntry
	{
		DWORD id; // 军衔编号
		char name[32]; // 名称
		DWORD needlevel; // 需要等级
		DWORD needprestige; // 需要声望
		DWORD maxcontri; // 功勋上限
		DWORD dayconsume; // 每日消耗
		DWORD maxprestige; // 声望上限
		DWORD paymodulus; // 税收工资
		DWORD damadd; // 增加攻击
		DWORD payticket; // 福利铜币
		DWORD skillpoint; // 技能点数

		virtual const char* getClassName() const { return "声望军衔表"; }
		static const char* getFileName() { return "MilitaryRankDataBase.tbl"; }
		void fill(const MilitaryRankDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			strncpy(this->name, base.name, 32);
			this->needlevel = base.needlevel;
			this->needprestige = base.needprestige;
			this->maxcontri = base.maxcontri;
			this->dayconsume = base.dayconsume;
			this->maxprestige = base.maxprestige;
			this->paymodulus = base.paymodulus;
			this->damadd = base.damadd;
			this->payticket = base.payticket;
			this->skillpoint = base.skillpoint;
		}
		void reset()
		{
			this->id = 0;
			this->name[0] = '\0';
			this->needlevel = 0;
			this->needprestige = 0;
			this->maxcontri = 0;
			this->dayconsume = 0;
			this->maxprestige = 0;
			this->paymodulus = 0;
			this->damadd = 0;
			this->payticket = 0;
			this->skillpoint = 0;
		}
	};
	typedef zDataBM<zMilitaryRankDataBaseEntry, MilitaryRankDataBase> MilitaryRankDataBaseManager;
}
#endif

