//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: NPC喊话表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct NpcTalkDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 编号
	char content[256]; // 喊话内容
};
#pragma pack()

#if false
namespace table
{
	// NPC喊话表
	struct zNpcTalkDataBaseEntry : public zEntry
	{
		DWORD id; // 编号
		char content[256]; // 喊话内容

		virtual const char* getClassName() const { return "NPC喊话表"; }
		static const char* getFileName() { return "NpcTalkDataBase.tbl"; }
		void fill(const NpcTalkDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			strncpy(this->content, base.content, 256);
		}
		void reset()
		{
			this->id = 0;
			this->content[0] = '\0';
		}
	};
	typedef zDataBM<zNpcTalkDataBaseEntry, NpcTalkDataBase> NpcTalkDataBaseManager;
}
#endif

