//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 宠物技能等级表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct PetSkillLevelBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 技能编号
	DWORD baseid; // 一级技能
	DWORD level; // 技能等级
	DWORD nextskillid; // 下一级技能
	DWORD fix; // 固定技能
	DWORD skillcardid; // 技能卡ID
	DWORD skillscore; // 评分
	DWORD lastskillid; // 上一级技能
};
#pragma pack()

#if false
namespace table
{
	// 宠物技能等级表
	struct zPetSkillLevelBaseEntry : public zEntry
	{
		DWORD id; // 技能编号
		DWORD baseid; // 一级技能
		DWORD level; // 技能等级
		DWORD nextskillid; // 下一级技能
		DWORD fix; // 固定技能
		DWORD skillcardid; // 技能卡ID
		DWORD skillscore; // 评分
		DWORD lastskillid; // 上一级技能

		virtual const char* getClassName() const { return "宠物技能等级表"; }
		static const char* getFileName() { return "PetSkillLevelBase.tbl"; }
		void fill(const PetSkillLevelBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			this->baseid = base.baseid;
			this->level = base.level;
			this->nextskillid = base.nextskillid;
			this->fix = base.fix;
			this->skillcardid = base.skillcardid;
			this->skillscore = base.skillscore;
			this->lastskillid = base.lastskillid;
		}
		void reset()
		{
			this->id = 0;
			this->baseid = 0;
			this->level = 0;
			this->nextskillid = 0;
			this->fix = 0;
			this->skillcardid = 0;
			this->skillscore = 0;
			this->lastskillid = 0;
		}
	};
	typedef zDataBM<zPetSkillLevelBaseEntry, PetSkillLevelBase> PetSkillLevelBaseManager;
}
#endif

