//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 宠物技能等级表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct PetSkillCardBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 技能卡ID
	DWORD skillid; // 技能编号
	DWORD level; // 技能等级
};
#pragma pack()

#if false
namespace table
{
	// 宠物技能等级表
	struct zPetSkillCardBaseEntry : public zEntry
	{
		DWORD id; // 技能卡ID
		DWORD skillid; // 技能编号
		DWORD level; // 技能等级

		virtual const char* getClassName() const { return "宠物技能等级表"; }
		static const char* getFileName() { return "PetSkillCardBase.tbl"; }
		void fill(const PetSkillCardBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			this->skillid = base.skillid;
			this->level = base.level;
		}
		void reset()
		{
			this->id = 0;
			this->skillid = 0;
			this->level = 0;
		}
	};
	typedef zDataBM<zPetSkillCardBaseEntry, PetSkillCardBase> PetSkillCardBaseManager;
}
#endif

