//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 极速狂飙道具表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct RunningItemDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 道具ID
	char name[32]; // 道具名字
	DWORD target; // 释放对象
	DWORD percent; // 获得概率
};
#pragma pack()

#if false
namespace table
{
	// 极速狂飙道具表
	struct zRunningItemDataBaseEntry : public zEntry
	{
		DWORD id; // 道具ID
		char name[32]; // 道具名字
		DWORD target; // 释放对象
		DWORD percent; // 获得概率

		virtual const char* getClassName() const { return "极速狂飙道具表"; }
		static const char* getFileName() { return "RunningItemDataBase.tbl"; }
		void fill(const RunningItemDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			strncpy(this->name, base.name, 32);
			this->target = base.target;
			this->percent = base.percent;
		}
		void reset()
		{
			this->id = 0;
			this->name[0] = '\0';
			this->target = 0;
			this->percent = 0;
		}
	};
	typedef zDataBM<zRunningItemDataBaseEntry, RunningItemDataBase> RunningItemDataBaseManager;
}
#endif

