//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 圣石表.xlsm SHEET: Sheet1 KEY: stoneid + quality + level

#pragma once
#pragma pack(1)
struct SacredStoneDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(stoneid, quality, level); }

	WORD level; // 等级
	WORD quality; // 品质
	DWORD stoneid; // 圣石ID
	DWORD pdam; // 物攻
	DWORD mdam; // 魔攻
	DWORD pdef; // 物防
	DWORD mdef; // 魔防
	DWORD maxhp; // 生命
	DWORD totalexp; // 携带魔阵经验和
	DWORD fee; // 需要绑银
	DWORD userlevel; // 需要等级
};
#pragma pack()

#if false
namespace table
{
	// 圣石表
	struct zSacredStoneDataBaseEntry : public zEntry
	{
		WORD level; // 等级
		WORD quality; // 品质
		DWORD stoneid; // 圣石ID
		DWORD pdam; // 物攻
		DWORD mdam; // 魔攻
		DWORD pdef; // 物防
		DWORD mdef; // 魔防
		DWORD maxhp; // 生命
		DWORD totalexp; // 携带魔阵经验和
		DWORD fee; // 需要绑银
		DWORD userlevel; // 需要等级

		virtual const char* getClassName() const { return "圣石表"; }
		static const char* getFileName() { return "SacredStoneDataBase.tbl"; }
		void fill(const SacredStoneDataBase& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			this->quality = base.quality;
			this->stoneid = base.stoneid;
			this->pdam = base.pdam;
			this->mdam = base.mdam;
			this->pdef = base.pdef;
			this->mdef = base.mdef;
			this->maxhp = base.maxhp;
			this->totalexp = base.totalexp;
			this->fee = base.fee;
			this->userlevel = base.userlevel;
		}
		void reset()
		{
			this->level = 0;
			this->quality = 0;
			this->stoneid = 0;
			this->pdam = 0;
			this->mdam = 0;
			this->pdef = 0;
			this->mdef = 0;
			this->maxhp = 0;
			this->totalexp = 0;
			this->fee = 0;
			this->userlevel = 0;
		}
	};
	typedef zDataBM<zSacredStoneDataBaseEntry, SacredStoneDataBase> SacredStoneDataBaseManager;
}
#endif

