//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 神座奖励表.xlsm SHEET: Sheet1 KEY: skillID + skillLevel

#pragma once
#pragma pack(1)
struct StarsDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(skillID, skillLevel); }

	WORD skillLevel; // 等级
	WORD skillID; // 编号
	DWORD dwPdam; // 物攻
	DWORD dwMdam; // 魔攻
	DWORD dwPdef; // 物防
	DWORD dwMdef; // 魔防
	DWORD dwHp; // 生命
};
#pragma pack()

#if false
namespace table
{
	// 神座奖励表
	struct zStarsDataBaseEntry : public zEntry
	{
		WORD skillLevel; // 等级
		WORD skillID; // 编号
		DWORD dwPdam; // 物攻
		DWORD dwMdam; // 魔攻
		DWORD dwPdef; // 物防
		DWORD dwMdef; // 魔防
		DWORD dwHp; // 生命

		virtual const char* getClassName() const { return "神座奖励表"; }
		static const char* getFileName() { return "StarsDataBase.tbl"; }
		void fill(const StarsDataBase& base)
		{
			this->id = base.getUniqueID();

			this->skillLevel = base.skillLevel;
			this->skillID = base.skillID;
			this->dwPdam = base.dwPdam;
			this->dwMdam = base.dwMdam;
			this->dwPdef = base.dwPdef;
			this->dwMdef = base.dwMdef;
			this->dwHp = base.dwHp;
		}
		void reset()
		{
			this->skillLevel = 0;
			this->skillID = 0;
			this->dwPdam = 0;
			this->dwMdam = 0;
			this->dwPdef = 0;
			this->dwMdef = 0;
			this->dwHp = 0;
		}
	};
	typedef zDataBM<zStarsDataBaseEntry, StarsDataBase> StarsDataBaseManager;
}
#endif

