//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: Store_商城表.xlsx SHEET: 商城基本 KEY: index

#pragma once
#pragma pack(1)
struct StoreDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(index); }

	DWORD index; // 索引ID
	BYTE store_id; // 商城ID
	DWORD item_id; // 道具ID
	DWORD pile_num; // 叠加数量
	BYTE money_type; // 购买货币类型
	DWORD buy_price; // 单价
	DWORD off_price; // 折后单价
	DWORD day_maxnum; // 每日限购数量
	DWORD ser_maxnum; // 全服可售总数
	BYTE vip_lev; // VIP等级限制
	WORD lev; // 主角等级限制
	BYTE is_off; // 是否开启打折
	BYTE is_out; // 是否下架
};
#pragma pack()

#if false
namespace table
{
	// Store_商城表
	struct zStoreDataBaseEntry : public zEntry
	{
		DWORD index; // 索引ID
		BYTE store_id; // 商城ID
		DWORD item_id; // 道具ID
		DWORD pile_num; // 叠加数量
		BYTE money_type; // 购买货币类型
		DWORD buy_price; // 单价
		DWORD off_price; // 折后单价
		DWORD day_maxnum; // 每日限购数量
		DWORD ser_maxnum; // 全服可售总数
		BYTE vip_lev; // VIP等级限制
		WORD lev; // 主角等级限制
		BYTE is_off; // 是否开启打折
		BYTE is_out; // 是否下架

		virtual const char* getClassName() const { return "Store_商城表"; }
		static const char* getFileName() { return "StoreDataBase.tbl"; }
		void fill(const StoreDataBase& base)
		{
			this->id = base.getUniqueID();

			this->index = base.index;
			this->store_id = base.store_id;
			this->item_id = base.item_id;
			this->pile_num = base.pile_num;
			this->money_type = base.money_type;
			this->buy_price = base.buy_price;
			this->off_price = base.off_price;
			this->day_maxnum = base.day_maxnum;
			this->ser_maxnum = base.ser_maxnum;
			this->vip_lev = base.vip_lev;
			this->lev = base.lev;
			this->is_off = base.is_off;
			this->is_out = base.is_out;
		}
		void reset()
		{
			this->index = 0;
			this->store_id = 0;
			this->item_id = 0;
			this->pile_num = 0;
			this->money_type = 0;
			this->buy_price = 0;
			this->off_price = 0;
			this->day_maxnum = 0;
			this->ser_maxnum = 0;
			this->vip_lev = 0;
			this->lev = 0;
			this->is_off = 0;
			this->is_out = 0;
		}
	};
	typedef zDataBM<zStoreDataBaseEntry, StoreDataBase> StoreDataBaseManager;
}
#endif

