//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 九宫格表.xlsm SHEET: Sheet1 KEY: id + sid

#pragma once
#pragma pack(1)
struct TreasureBase
{
	DWORD getUniqueID() const { return usage_id_hash(id, sid); }

	DWORD sid; // 流水号
	DWORD id; // 宝箱ID
	DWORD number; // 格子数
	DWORD times; // 重复次数
	DWORD price; // 基本费用
	char group1[1024]; // 第一组
	char group2[1024]; // 第二组
	char group3[1024]; // 第三组
	char group4[1024]; // 第四组
	char group5[1024]; // 第五组
	char freegroup1[1024]; // 免费第一组
	char freegroup2[1024]; // 免费第二组
};
#pragma pack()

#if false
namespace table
{
	// 九宫格表
	struct zTreasureBaseEntry : public zEntry
	{
		DWORD sid; // 流水号
		DWORD id; // 宝箱ID
		DWORD number; // 格子数
		DWORD times; // 重复次数
		DWORD price; // 基本费用
		char group1[1024]; // 第一组
		char group2[1024]; // 第二组
		char group3[1024]; // 第三组
		char group4[1024]; // 第四组
		char group5[1024]; // 第五组
		char freegroup1[1024]; // 免费第一组
		char freegroup2[1024]; // 免费第二组

		virtual const char* getClassName() const { return "九宫格表"; }
		static const char* getFileName() { return "TreasureBase.tbl"; }
		void fill(const TreasureBase& base)
		{
			this->id = base.getUniqueID();

			this->sid = base.sid;
			this->id = base.id;
			this->number = base.number;
			this->times = base.times;
			this->price = base.price;
			strncpy(this->group1, base.group1, 1024);
			strncpy(this->group2, base.group2, 1024);
			strncpy(this->group3, base.group3, 1024);
			strncpy(this->group4, base.group4, 1024);
			strncpy(this->group5, base.group5, 1024);
			strncpy(this->freegroup1, base.freegroup1, 1024);
			strncpy(this->freegroup2, base.freegroup2, 1024);
		}
		void reset()
		{
			this->sid = 0;
			this->id = 0;
			this->number = 0;
			this->times = 0;
			this->price = 0;
			this->group1[0] = '\0';
			this->group2[0] = '\0';
			this->group3[0] = '\0';
			this->group4[0] = '\0';
			this->group5[0] = '\0';
			this->freegroup1[0] = '\0';
			this->freegroup2[0] = '\0';
		}
	};
	typedef zDataBM<zTreasureBaseEntry, TreasureBase> TreasureBaseManager;
}
#endif

