//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: Role属性设定.xlsx SHEET: 战士 KEY: level

#pragma once
#pragma pack(1)
struct UserSoldierDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(level); }

	DWORD level; // 等级
	DWORD tizhi; // 体质
	DWORD liliang; // 力量
	DWORD zhili; // 智力
	DWORD jingshen; // 精神
	DWORD minjie; // 敏捷
	DWORD maxhp; // 生命上限
	DWORD maxsp; // 法力上限
	DWORD pdam; // 物理攻击
	DWORD pdef; // 物理防御
	DWORD mdam; // 法术攻击
	DWORD mdef; // 法术防御
	DWORD lucky; // 物理致命
	DWORD mlucky; // 法术致命
	DWORD phit; // 命中
	DWORD hide; // 闪避
};
#pragma pack()

#if false
namespace table
{
	// Role属性设定
	struct zUserSoldierDataBaseEntry : public zEntry
	{
		DWORD level; // 等级
		DWORD tizhi; // 体质
		DWORD liliang; // 力量
		DWORD zhili; // 智力
		DWORD jingshen; // 精神
		DWORD minjie; // 敏捷
		DWORD maxhp; // 生命上限
		DWORD maxsp; // 法力上限
		DWORD pdam; // 物理攻击
		DWORD pdef; // 物理防御
		DWORD mdam; // 法术攻击
		DWORD mdef; // 法术防御
		DWORD lucky; // 物理致命
		DWORD mlucky; // 法术致命
		DWORD phit; // 命中
		DWORD hide; // 闪避

		virtual const char* getClassName() const { return "Role属性设定"; }
		static const char* getFileName() { return "UserSoldierDataBase.tbl"; }
		void fill(const UserSoldierDataBase& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			this->tizhi = base.tizhi;
			this->liliang = base.liliang;
			this->zhili = base.zhili;
			this->jingshen = base.jingshen;
			this->minjie = base.minjie;
			this->maxhp = base.maxhp;
			this->maxsp = base.maxsp;
			this->pdam = base.pdam;
			this->pdef = base.pdef;
			this->mdam = base.mdam;
			this->mdef = base.mdef;
			this->lucky = base.lucky;
			this->mlucky = base.mlucky;
			this->phit = base.phit;
			this->hide = base.hide;
		}
		void reset()
		{
			this->level = 0;
			this->tizhi = 0;
			this->liliang = 0;
			this->zhili = 0;
			this->jingshen = 0;
			this->minjie = 0;
			this->maxhp = 0;
			this->maxsp = 0;
			this->pdam = 0;
			this->pdef = 0;
			this->mdam = 0;
			this->mdef = 0;
			this->lucky = 0;
			this->mlucky = 0;
			this->phit = 0;
			this->hide = 0;
		}
	};
	typedef zDataBM<zUserSoldierDataBaseEntry, UserSoldierDataBase> UserSoldierDataBaseManager;
}
#endif

