//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 交流表情表.xlsm SHEET: Sheet1

#pragma once
#pragma pack(1)
struct UserColEmotionDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(); }

	DWORD id; // 编号
	DWORD consume; // 消耗
	DWORD level; // 需求等级
	DWORD type; // 类型
};
#pragma pack()

#if false
namespace table
{
	// 交流表情表
	struct zUserColEmotionDataBaseEntry : public zEntry
	{
		DWORD id; // 编号
		DWORD consume; // 消耗
		DWORD level; // 需求等级
		DWORD type; // 类型

		virtual const char* getClassName() const { return "交流表情表"; }
		static const char* getFileName() { return "UserColEmotionDataBase.tbl"; }
		void fill(const UserColEmotionDataBase& base)
		{
			this->id = base.id;
			this->consume = base.consume;
			this->level = base.level;
			this->type = base.type;
		}
		void reset()
		{
			this->id = 0;
			this->consume = 0;
			this->level = 0;
			this->type = 0;
		}
	};
	typedef zDataBM<zUserColEmotionDataBaseEntry, UserColEmotionDataBase> UserColEmotionDataBaseManager;
}
#endif

