//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 白色装备表.xlsm SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct WhiteEquipDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // 道具ID
	char maxdur[32]; // 装备耐久
	DWORD maxhp; // 生命值上限
	DWORD pdam; // 物理攻击
	DWORD mdam; // 化学攻击
	DWORD phit; // 物理命中
	DWORD mhit; // 化学命中
	DWORD pdef; // 物理防御
	DWORD mdef; // 化学防御
	DWORD rndam; // 热能攻击
	DWORD gbdam; // 光波攻击
	DWORD sbdam; // 声波攻击
	DWORD shdam; // 生化攻击
	char rates[128]; // 鉴定概率
	DWORD pdamext; // 物攻附加
	DWORD mdamext; // 化攻附加
	DWORD pdefext; // 物防附加
	DWORD mdefext; // 化防附加
	DWORD maxhpext; // 生命值附加
	DWORD attack; // 是否可骑乘攻击
	DWORD rndef; // 热能防御
	DWORD gbdef; // 光波防御
	DWORD sbdef; // 声波防御
	DWORD shdef; // 生化防御
	DWORD pdamper; // 物攻提升
	DWORD mdamper; // 化攻提升
	DWORD pdefper; // 物防提升
	DWORD mdefper; // 化防提升
	DWORD maxhpper; // 生命值提升
	DWORD frozendef; // 抗冰冻
	DWORD silentdef; // 抗静默
	DWORD changedef; // 抗变形
	DWORD faintdef; // 抗眩晕
	DWORD speedsubdef; // 抗减速
	DWORD persubecho; // 反伤减免
};
#pragma pack()

#if false
namespace table
{
	// 白色装备表
	struct zWhiteEquipDataBaseEntry : public zEntry
	{
		DWORD id; // 道具ID
		char maxdur[32]; // 装备耐久
		DWORD maxhp; // 生命值上限
		DWORD pdam; // 物理攻击
		DWORD mdam; // 化学攻击
		DWORD phit; // 物理命中
		DWORD mhit; // 化学命中
		DWORD pdef; // 物理防御
		DWORD mdef; // 化学防御
		DWORD rndam; // 热能攻击
		DWORD gbdam; // 光波攻击
		DWORD sbdam; // 声波攻击
		DWORD shdam; // 生化攻击
		char rates[128]; // 鉴定概率
		DWORD pdamext; // 物攻附加
		DWORD mdamext; // 化攻附加
		DWORD pdefext; // 物防附加
		DWORD mdefext; // 化防附加
		DWORD maxhpext; // 生命值附加
		DWORD attack; // 是否可骑乘攻击
		DWORD rndef; // 热能防御
		DWORD gbdef; // 光波防御
		DWORD sbdef; // 声波防御
		DWORD shdef; // 生化防御
		DWORD pdamper; // 物攻提升
		DWORD mdamper; // 化攻提升
		DWORD pdefper; // 物防提升
		DWORD mdefper; // 化防提升
		DWORD maxhpper; // 生命值提升
		DWORD frozendef; // 抗冰冻
		DWORD silentdef; // 抗静默
		DWORD changedef; // 抗变形
		DWORD faintdef; // 抗眩晕
		DWORD speedsubdef; // 抗减速
		DWORD persubecho; // 反伤减免

		virtual const char* getClassName() const { return "白色装备表"; }
		static const char* getFileName() { return "WhiteEquipDataBase.tbl"; }
		void fill(const WhiteEquipDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			strncpy(this->maxdur, base.maxdur, 32);
			this->maxhp = base.maxhp;
			this->pdam = base.pdam;
			this->mdam = base.mdam;
			this->phit = base.phit;
			this->mhit = base.mhit;
			this->pdef = base.pdef;
			this->mdef = base.mdef;
			this->rndam = base.rndam;
			this->gbdam = base.gbdam;
			this->sbdam = base.sbdam;
			this->shdam = base.shdam;
			strncpy(this->rates, base.rates, 128);
			this->pdamext = base.pdamext;
			this->mdamext = base.mdamext;
			this->pdefext = base.pdefext;
			this->mdefext = base.mdefext;
			this->maxhpext = base.maxhpext;
			this->attack = base.attack;
			this->rndef = base.rndef;
			this->gbdef = base.gbdef;
			this->sbdef = base.sbdef;
			this->shdef = base.shdef;
			this->pdamper = base.pdamper;
			this->mdamper = base.mdamper;
			this->pdefper = base.pdefper;
			this->mdefper = base.mdefper;
			this->maxhpper = base.maxhpper;
			this->frozendef = base.frozendef;
			this->silentdef = base.silentdef;
			this->changedef = base.changedef;
			this->faintdef = base.faintdef;
			this->speedsubdef = base.speedsubdef;
			this->persubecho = base.persubecho;
		}
		void reset()
		{
			this->id = 0;
			this->maxdur[0] = '\0';
			this->maxhp = 0;
			this->pdam = 0;
			this->mdam = 0;
			this->phit = 0;
			this->mhit = 0;
			this->pdef = 0;
			this->mdef = 0;
			this->rndam = 0;
			this->gbdam = 0;
			this->sbdam = 0;
			this->shdam = 0;
			this->rates[0] = '\0';
			this->pdamext = 0;
			this->mdamext = 0;
			this->pdefext = 0;
			this->mdefext = 0;
			this->maxhpext = 0;
			this->attack = 0;
			this->rndef = 0;
			this->gbdef = 0;
			this->sbdef = 0;
			this->shdef = 0;
			this->pdamper = 0;
			this->mdamper = 0;
			this->pdefper = 0;
			this->mdefper = 0;
			this->maxhpper = 0;
			this->frozendef = 0;
			this->silentdef = 0;
			this->changedef = 0;
			this->faintdef = 0;
			this->speedsubdef = 0;
			this->persubecho = 0;
		}
	};
	typedef zDataBM<zWhiteEquipDataBaseEntry, WhiteEquipDataBase> WhiteEquipDataBaseManager;
}
#endif

