//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 翼魂品质表.xlsm SHEET: Sheet1 KEY: quality

#pragma once
#pragma pack(1)
struct WingSpiritQualityBase
{
	DWORD getUniqueID() const { return usage_id_hash(quality); }

	DWORD quality; // 翼魂品质
	DWORD spiritpiece; // 增加魂性
	DWORD spiritprice; // 入魂费用
	DWORD composeprice; // 合成费用
};
#pragma pack()

#if false
namespace table
{
	// 翼魂品质表
	struct zWingSpiritQualityBaseEntry : public zEntry
	{
		DWORD quality; // 翼魂品质
		DWORD spiritpiece; // 增加魂性
		DWORD spiritprice; // 入魂费用
		DWORD composeprice; // 合成费用

		virtual const char* getClassName() const { return "翼魂品质表"; }
		static const char* getFileName() { return "WingSpiritQualityBase.tbl"; }
		void fill(const WingSpiritQualityBase& base)
		{
			this->id = base.getUniqueID();

			this->quality = base.quality;
			this->spiritpiece = base.spiritpiece;
			this->spiritprice = base.spiritprice;
			this->composeprice = base.composeprice;
		}
		void reset()
		{
			this->quality = 0;
			this->spiritpiece = 0;
			this->spiritprice = 0;
			this->composeprice = 0;
		}
	};
	typedef zDataBM<zWingSpiritQualityBaseEntry, WingSpiritQualityBase> WingSpiritQualityBaseManager;
}
#endif

