//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 羽翼炼化表.xlsm SHEET: Sheet1 KEY: level

#pragma once
#pragma pack(1)
struct WingRefinementBase
{
	DWORD getUniqueID() const { return usage_id_hash(level); }

	DWORD level; // 炼化等级
	DWORD successrate; // 成功几率
	DWORD falselevel; // 失败后等级
	DWORD pdam; // 物攻附加
	DWORD mdam; // 化攻附加
	DWORD pdef; // 物防附加
	DWORD mdef; // 化防附加
	DWORD maxhp; // 生命值附加
	DWORD needmoney; // 需要金钱
	DWORD neednum; // 需要个数
	DWORD needrolelevel; // 需求人物等级
};
#pragma pack()

#if false
namespace table
{
	// 羽翼炼化表
	struct zWingRefinementBaseEntry : public zEntry
	{
		DWORD level; // 炼化等级
		DWORD successrate; // 成功几率
		DWORD falselevel; // 失败后等级
		DWORD pdam; // 物攻附加
		DWORD mdam; // 化攻附加
		DWORD pdef; // 物防附加
		DWORD mdef; // 化防附加
		DWORD maxhp; // 生命值附加
		DWORD needmoney; // 需要金钱
		DWORD neednum; // 需要个数
		DWORD needrolelevel; // 需求人物等级

		virtual const char* getClassName() const { return "羽翼炼化表"; }
		static const char* getFileName() { return "WingRefinementBase.tbl"; }
		void fill(const WingRefinementBase& base)
		{
			this->id = base.getUniqueID();

			this->level = base.level;
			this->successrate = base.successrate;
			this->falselevel = base.falselevel;
			this->pdam = base.pdam;
			this->mdam = base.mdam;
			this->pdef = base.pdef;
			this->mdef = base.mdef;
			this->maxhp = base.maxhp;
			this->needmoney = base.needmoney;
			this->neednum = base.neednum;
			this->needrolelevel = base.needrolelevel;
		}
		void reset()
		{
			this->level = 0;
			this->successrate = 0;
			this->falselevel = 0;
			this->pdam = 0;
			this->mdam = 0;
			this->pdef = 0;
			this->mdef = 0;
			this->maxhp = 0;
			this->needmoney = 0;
			this->neednum = 0;
			this->needrolelevel = 0;
		}
	};
	typedef zDataBM<zWingRefinementBaseEntry, WingRefinementBase> WingRefinementBaseManager;
}
#endif

